apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: data-pipeline
  name: spark-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "configmaps", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "delete", "deletecollection", "update"]
- apiGroups: [""]  # Core API group for events
  resources: ["events"]
  verbs: ["create", "patch"]