apiVersion: v1
kind: Pod
metadata:
  name: test-pvc-pod
  namespace: data-pipeline
spec:
  containers:
  - name: test-container
    image: busybox
    command: [ "sh", "-c", "echo 'PVC is now bound!' > /mnt/data/hello.txt && sleep 3600" ]
    volumeMounts:
    - name: test-storage
      mountPath: /mnt/data
  volumes:
  - name: test-storage
    persistentVolumeClaim:
      claimName: single-access-pvc

